### ISSUE TITLE
Add `electron-builder` support

### ISSUE THREAD

**Issue by JohnnyYeen** [herberttn/bytenode-webpack-plugin#11]
Hi there, you've done an incredible and exciting job on electron-forge!
However, as we can see there're tons of projects  built within electron-builder. 
So are there any plans for electron-builder supporting?
Really appreciated!

**Comment by herberttn** [comment]
@JohnnyYeen hello!

This project is not something specific to `electron-forge`, it's a `webpack` plugin for `bytenode`, so you can use it with any project that uses `webpack` (that being plain `node`, or `electron`).

`electron-forge` uses `webpack` in a very specific way and that's why we had to specifically add extra support for it. `electron-builder` doesn't require the use of `webpack` and I don't think `electron-builder` uses `webpack` by itself (as `electron-forge` does), so I believe it's up to you if you want to use both `webpack` and `bytenode-webpack-plugin`.

Have you tried to use `bytenode-webpack-plugin` with `electron-builder`? If so, can you post some details about your experience and the problems you encountered? Maybe there is a simple fix for the bug you're facing?

And do you have any suggestion on how we may go about improving our currently very simple documentation to better explain the relationship this plugin plays with `webpack`, `electron-forge`, `electron-builder`, etc?

Thank you for the appreciation!

**Comment by josteph** [comment]
I think it's already supported out of the box, just need to follow the usual pattern in the example repository. I can confirm that this works with `electron-builder`, great work!

**Comment by jjeff** [comment]
Sounds like this is a solved problem. Closing. Please reopen if I'm mistaken.
