### ISSUE TITLE
electron forge + multiple renders

### ISSUE THREAD

**Issue by iamisti** [herberttn/bytenode-webpack-plugin#33]
Is it possible to use this plugin if I have an electron application with multiple renders?

I have 3 renderers with node target and one with nodeIntegration=false, this cannnot change.

Please advise! Thank you.

**Comment by herberttn** [comment]
Hello @iamisti! Yes, you can use this plugin in electron main and/or renderers separately. Since each is a separate webpack configuration, you'd need to enable it in each. Our current understanding is that it is currently not possible to use in renderers with `nodeIntegration=false`, as the implementation needs access to node to decode the bytecode.
