### ISSUE TITLE
Can I exclude some files?

### ISSUE THREAD

**Issue by Cinux-Chosan** [herberttn/bytenode-webpack-plugin#9]
Because of some known issues of bytenode, I need to exclude some files to be compiled into jsc, But there seems no option for this?

**Comment by herberttn** [comment]
@Cinux-Chosan Try [`v2.2.0`](https://github.com/herberttn/bytenode-webpack-plugin/releases/tag/v2.2.0)

**Comment by trensc** [comment]
Is there no way to prevent a file from being modified by the plugin? I know that it currently generates a compiled.js file, but is it possible to leave the file as it was before the build process?

I have an Electron app, and it includes a small preload.ts file that exposes ipcRenderer in the Window context. The issue is that now preload.js has been modified to include code that imports the compiled file to execute it, which I don't think is possible in the browser context.

<img width="552" alt="Capture d’écran 2023-07-13 à 00 10 29" src="https://github.com/herberttn/bytenode-webpack-plugin/assets/59595251/c3bbb6b5-a78f-4d69-bd93-f1925c08be99">

<img width="183" alt="Capture d’écran 2023-07-13 à 00 11 09" src="https://github.com/herberttn/bytenode-webpack-plugin/assets/59595251/bf0bd32f-4310-48e8-a9bb-27097a3599a1">

_The error and the files i'm getting on build._

**Comment by herberttn** [comment]
@Atomoox can you try using the `exclude` option?
https://github.com/herberttn/bytenode-webpack-plugin/blob/1b8d19be49f083c9dc83bfd11c9b3eed1035d989/src/types.ts#L12

If it doesn't work for you, please file a new issue with a reproduction repository for me to try.
